name: KOTANI BACKEND TEST CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      INFURA_KEY: ${{ secrets.I_K }}
      SENDER_PRIVATE_KEY: ${{ secrets.S_P_K }}
      SENDER_ADDRESS: ${{ secrets.S_A }}
      RECEIVER_ADDRESS: ${{ secrets.R_A }}
      INVALID_SENDER_ADDRESS: ${{ secrets.I_S_A }}
      CI: true
      MONGODB_URI: mongodb://localhost/test
    strategy:
      matrix:
        node-version: ["16.x"]
        mongodb-version: ["6.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up node js to run on ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: yarn
      - run: yarn test
